import React, { useState } from 'react';
import axios from 'axios';
import { Lightbulb, Loader2, TrendingUp, PackagePlus, ArrowRight } from 'lucide-react';

export default function Playbook() {
  const [recommendations, setRecommendations] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState('');

  const runDecisionEngine = async () => {
    setIsGenerating(true);
    setError('');
    
    try {
      const response = await axios.get('http://localhost:8000/api/generate-recommendations');
      setRecommendations(response.data.recommendations);
      
      if (response.data.recommendations.length === 0) {
        setError("Data analyzed, but no actionable bundle rules found for this period.");
      }
    } catch (err) {
      console.error(err);
      setError("Error running engine. Please upload data on the Data Ingestion page first.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="animate-fade-in-up">
      
      {/* PAGE HEADER */}
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 flex items-center gap-3">
          <Lightbulb className="text-amber-500" size={32} />
          Strategic Playbook
        </h2>
        <p className="text-gray-500 mt-2">Actionable business strategies generated by merging Prophet forecasts with Apriori rules.</p>
      </div>

      {/* CONTROL PANEL */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 mb-8 flex justify-between items-center">
        <div>
          <h3 className="font-semibold text-gray-800">OPTIMA Decision Engine</h3>
          <p className="text-sm text-gray-500">Run the logic layer to translate math into marketing advice.</p>
        </div>
        <button 
          onClick={runDecisionEngine}
          disabled={isGenerating}
          className="bg-gray-900 text-white px-6 py-2 rounded-lg font-medium hover:bg-black disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center gap-2 transition-colors shadow-sm"
        >
          {isGenerating ? <><Loader2 className="animate-spin w-5 h-5" /> Compiling Playbook...</> : 'Generate Strategies'}
        </button>
      </div>

      {error && (
        <div className="bg-amber-50 text-amber-800 p-4 rounded-lg mb-8 text-sm font-medium border border-amber-200">
          {error}
        </div>
      )}

      {/* RESULTS DISPLAY */}
      {recommendations.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {recommendations.map((rec, index) => (
            <div key={index} className="bg-white rounded-xl shadow-sm border border-gray-200 hover:shadow-lg transition-all overflow-hidden flex flex-col h-full group">
              
              <div className={`px-6 py-4 border-b flex items-start justify-between ${rec.type === 'Bundle Strategy' ? 'bg-indigo-50 border-indigo-100' : 'bg-blue-50 border-blue-100'}`}>
                <div>
                  <span className={`text-xs font-bold uppercase tracking-wider px-2 py-1 rounded-md ${rec.type === 'Bundle Strategy' ? 'bg-indigo-200 text-indigo-800' : 'bg-blue-200 text-blue-800'}`}>
                    {rec.type}
                  </span>
                  <h3 className="text-lg font-bold text-gray-900 mt-3 group-hover:text-indigo-600 transition-colors">
                    {rec.target_item}
                  </h3>
                </div>
                {rec.type === "Bundle Strategy" ? <PackagePlus className="text-indigo-500 mt-1" /> : <TrendingUp className="text-blue-500 mt-1" />}
              </div>
              
              <div className="p-6 flex-grow flex flex-col justify-between">
                <div>
                  <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Recommended Action</p>
                  <p className="text-gray-900 font-medium mb-6 text-base">{rec.action}</p>
                  
                  <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                    <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2 flex items-center gap-1">
                      AI Justification <ArrowRight size={12} />
                    </p>
                    <p className="text-sm text-gray-600 leading-relaxed italic">"{rec.justification}"</p>
                  </div>
                </div>
              </div>
              
            </div>
          ))}
        </div>
      )}
    </div>
  );
}